### ISSUE TITLE
Staples not working correctly

### ISSUE THREAD

**Issue by ingolvjr** [vr4vet/Construction-sector#17]
The stapler can place staples on other staples, which looks bad
The staples also don't get destroyed or deactivated when you go to the next subtask

I did take images of this, but they didn't crop properly, Snipping tool doesn't really work on windows 11

**Comment by alxyzz** [comment]
thank you a lot, must have overlooked that at some point

**Comment by alxyzz** [comment]
fixed two days ago, thank you
